-- Cached narrative insight for staff wellbeing, generated by an LLM
-- from aggregate data. One per school per term.
CREATE TABLE "StaffWellbeingInsight" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "term" TEXT NOT NULL,
    "academicYear" TEXT NOT NULL,
    "narrativeJson" TEXT NOT NULL,
    "modelUsed" TEXT,
    "cohortSize" INTEGER NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StaffWellbeingInsight_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "StaffWellbeingInsight_schoolId_term_academicYear_key"
  ON "StaffWellbeingInsight"("schoolId", "term", "academicYear");
CREATE INDEX "StaffWellbeingInsight_schoolId_idx"
  ON "StaffWellbeingInsight"("schoolId");
